# Generated by Django 5.2.4 on 2025-07-21 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_no', models.CharField(db_column='Slot_No', max_length=100)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('vehicle', models.CharField(blank=True, db_column='Vehicle', max_length=100, null=True)),
                ('lot_id', models.CharField(db_column='Lot_ID', max_length=300)),
                ('road_name', models.CharField(db_column='Road_Name', max_length=255)),
                ('lot_type', models.CharField(blank=True, db_column='Lot_type', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='geom', srid=4326)),
            ],
            options={
                'db_table': 'parking_lots',
                'managed': False,
            },
        ),
    ]
