# Generated by Django 5.2.4 on 2025-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_booking_arrived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arrived', 'Arrived'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
