# Generated by Django 5.2.4 on 2025-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_bookingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PICKUP', 'PICKUP'), ('MOTORBIKE', 'MOTORBIKE'), ('TUKTUK', 'TUKTUK'), ('TANKER', 'TANKER'), ('CANTER', 'CANTER'), ('LORRY', 'LORRY'), ('MINIBUS', 'MINIBUS'), ('TRAILER', 'TRAILER')], default='PRIVATE', max_length=20),
        ),
    ]
