# Generated by Django 5.2.4 on 2025-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arrived', 'Arrived'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('illegal', 'Illegal')], default='active', max_length=10),
        ),
    ]
